# Generated by Django 6.0.2 on 2026-02-15 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_pet_species_profile_vaccinationrecord'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clinic',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='clinicvaccine',
            options={'ordering': ['clinic', 'vaccine']},
        ),
        migrations.AlterModelOptions(
            name='pet',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='tutor',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='vaccinationrecord',
            options={'ordering': ['-applied_at']},
        ),
        migrations.AlterModelOptions(
            name='vaccine',
            options={'ordering': ['name']},
        ),
    ]
